postgis:
  image: kartoza/postgis
  hostname: postgis
  ports:
  - "5432:5432"
  volumes:
  - ./postgis:/tmp/postgis
geoserver:
  build: geoserver
  hostname: geoserver
  ports:
  - "8080:8080"
  links:
  - postgis:postgis
  volumes:
  - ./geoserver_data:/srv/geoserver
  - ./geoserver:/tmp/geoserver
  - /home/ubuntu/tifs:/tifs
preview:
  build: preview
  hostname: preview
  ports:
  - "80:80"
  links:
  - geoserver:geoserver
